FROM harbor.ukserp.ac.uk/dare/hive-alleeex:3.1.3-r2
# TODO change base to new official apache container
#FROM apache/hive:3.1.3

LABEL org.opencontainers.image.source=https://github.com/SwanseaUniversityMedical/DARE-Hive
