apiVersion: v2
appVersion: 1.1.1
dependencies:
- condition: postgresql-ha.enabled
  name: postgresql-ha
  repository: https://charts.bitnami.com/bitnami
  version: 11.7.6
description: The Apache Hive ™ is a data warehouse software project built on top of
  Apache Hadoop for providing data query and analysis. Hive gives an SQL-like interface
  to query data stored in various databases and file systems that integrate with Hadoop.
home: https://hive.apache.org/
icon: https://hive.apache.org/images/hive_logo_medium.jpg
name: hive
sources:
- https://github.com/apache/hive
version: 1.1.1
