apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.fullname" . }}
    {{- include "hiveMetastore.labels" . | nindent 4 }}
data:
  metastore-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>metastore.thrift.uris</name>
            <value>thrift://{{ .Release.Name }}:9083</value>
            <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
        </property>
        <property>
            <name>metastore.task.threads.always</name>
            <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
        </property>
        <property>
            <name>metastore.expression.proxy</name>
            <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            {{- if .Values.mysql.enabled }}
            <value>com.mysql.cj.jdbc.Driver</value>
            {{- else }}
            <value>org.postgresql.Driver</value>
            {{- end }}
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            {{- if .Values.mysql.enabled }}
            <value>jdbc:mysql://{{ .Release.Name }}-{{ .Values.metastoreDb.hostname }}:{{ .Values.metastoreDb.port }}/{{ .Values.mysql.auth.database }}</value>
            {{- else }}
            <value>jdbc:postgresql://{{ .Values.metastoreDb.hostname }}:{{ .Values.metastoreDb.port }}/{{ .Values.metastoreDb.database }}</value>
            {{- end }}       
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            {{- if .Values.mysql.enabled }}
            <value>{{ .Values.mysql.auth.username }}</value>
            {{- else }}
            <value>{{ .Values.metastoreDb.auth.username }}</value>
            {{- end }}
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            {{- if .Values.mysql.enabled }}
            <value>{{ .Values.mysql.auth.password }}</value>
            {{- else }}
            <value>{{ .Values.metastoreDb.auth.password }}</value>
            {{- end }}
        </property>
        <property>
            <name>fs.s3a.access.key</name>
            <value>{{ .Values.minio.accessKey }}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>{{ .Values.minio.secretKey }}</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>{{ .Values.minio.endpoint }}</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
    </configuration>
