apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.fullname" . }}
    {{- include "hiveMetastore.labels" . | nindent 4 }}
data:
  metastore-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>metastore.thrift.uris</name>
            <value>thrift://{{ .Release.Name }}:9083</value>
            <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
        </property>
        <property>
            <name>metastore.task.threads.always</name>
            <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
        </property>
        <property>
            <name>metastore.expression.proxy</name>
            <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>org.postgresql.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            {{- if index .Values "postgresql-ha.overrideAddress" }}
            <value>jdbc:postgresql://{{ index .Values "postgresql-ha.overrideAddress" }}:5432/{{ index .Values "postgresql-ha.postgresql.database" }}</value>
            {{- else }}
            <value>jdbc:postgresql://{{ .Release.Name }}-postgresql-ha-pgpool:5432/{{ index .Values "postgresql-ha.postgresql.database" }}</value>
            {{- end }}
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>{{ index .Values "postgresql-ha.postgresql.username" }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>{{ index .Values "postgresql-ha.postgresql.password" }}</value>
        </property>
        <property>
            <name>fs.s3a.access.key</name>
            <value>{{ .Values.minio.accessKey }}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>{{ .Values.minio.secretKey }}</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>{{ .Values.minio.endpoint }}</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
    </configuration>
