{{- if eq (toString .Values.replicaCount) "1" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    {{- include "hiveMetastore.labels" $ | trim | nindent 4 }}
    app.kubernetes.io/component: metastore
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveMetastore.fullname" . }}
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hiveMetastore.fullname" . }}
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | trim | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hiveMetastore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | trim  | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: METASTORE_DB_HOSTNAME
              # have to use the 'index' method due to this bug https://github.com/helm/helm/issues/2192
              {{- if index .Values "postgresql-ha.overrideAddress" }}
              value: {{ index .Values "postgresql-ha.overrideAddress" }}
              {{- else }}
              value: {{ .Release.Name }}-postgresql-ha-pgpool
              {{- end }}
          ports:
            - name: tcp
              containerPort: 9083
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | trim  | nindent 12 }}
          volumeMounts:
          - name: hive-conf-templates
            mountPath: /opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml
            subPath: metastore-site.xml
      volumes:
      - name: hive-conf-templates
        configMap:
          name: {{ .Release.Name }}
{{- end }}