{{- if eq (toString .Values.replicaCount) "1" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    {{- include "hiveMetastore.labels" $ | trim | nindent 4 }}
    app.kubernetes.io/component: metastore
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveMetastore.fullname" . }}
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hiveMetastore.fullname" . }}
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
      {{- if .Values.annotations }}
      annotations:
        {{- with .Values.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | trim | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hiveMetastore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | trim  | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.overrideCommand }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: METASTORE_DB_HOSTNAME
              value: {{ .Release.Name }}-{{ .Values.metastoreHostname }}
            {{- with .Values.env }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          ports:
            - name: tcp
              containerPort: 9083
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | trim  | nindent 12 }}
          volumeMounts:
          - name: hive-conf-templates
            mountPath: /opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml
            subPath: metastore-site.xml
      volumes:
      - name: hive-conf-templates
        configMap:
          name: {{ .Release.Name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}